version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'speed-monitor'   
      MYSQL_USER: 'app-user'
      MYSQL_PASSWORD: 'Pa55word123!'
      MYSQL_ROOT_PASSWORD: 'Pa55word123!'
    ports:
      - '3306:3306'
  app:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links: 
      - db
    environment:
      DB_DATABASE: 'speed-monitor'   
      DB_USER: 'app-user'
      DB_PASSWORD: 'Pa55word123!'
      DB_HOST: db

volumes:
  db_data: {}