default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  database: <%= ENV.fetch('DB_DATABASE') %>
  host: <%= ENV.fetch('DB_HOST') %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>_test

production:
  <<: *default
